### ISSUE TITLE
Automatically post the transcript

### ISSUE THREAD

**Issue by yeungon** [vietspeak/bot#5]
- Using Airtable API

**Comment by dvbui** [comment]
You can use VietSpeak OJ Website (oj.vietspeak.org) to get the current transcript.
Examples
http://185.163.125.151:5000/tasks?number=98&level=Yellow
http://185.163.125.151:5000/tasks?number=98&level=Green
http://185.163.125.151:5000/tasks?number=99&level=Red

**Comment by yeungon** [comment]
closed as solved in #5d8dc28
